# Generated by Django 6.0.3 on 2026-06-16 19:02

import embed_video.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='demo_video_url',
            field=embed_video.fields.EmbedVideoField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='installation_video_url',
            field=embed_video.fields.EmbedVideoField(blank=True, null=True),
        ),
    ]
