# Generated by Django 6.0.3 on 2026-06-16 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='is_global',
            field=models.BooleanField(default=False),
        ),
    ]
