# Generated by Django 6.0.3 on 2026-06-18 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0002_coupon_is_global'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='is_unlimited',
            field=models.BooleanField(default=False),
        ),
    ]
