# Generated by Django 6.0.3 on 2026-03-26 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_dob_profile_gender_profile_phone_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('customer', 'Customer'), ('seller', 'Seller')], default='customer', max_length=10),
        ),
    ]
