# Generated by Django 6.0.3 on 2026-06-17 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_customer_account',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='is_seller_account',
            field=models.BooleanField(default=False),
        ),
    ]
