# Generated by Django 6.0.3 on 2026-04-08 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursevideo',
            name='notes',
            field=models.TextField(blank=True, help_text='Paste full HTML notes content for this video topic.', null=True),
        ),
    ]
