# Generated by Django 6.0.3 on 2026-06-16 19:02

import embed_video.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='is_free',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='course',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='coursevideo',
            name='youtube_url',
            field=embed_video.fields.EmbedVideoField(help_text='Paste normal YouTube URL'),
        ),
    ]
