# Generated by Django 6.0.3 on 2026-06-17 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_course_is_free_course_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='access_duration_months',
            field=models.IntegerField(choices=[(0, 'Lifetime'), (3, '3 Months'), (6, '6 Months')], default=0, help_text='0 means lifetime access'),
        ),
    ]
