# Generated by Django 6.0.3 on 2026-06-16 19:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_course_is_free_course_price_and_more'),
        ('orders', '0001_initial'),
        ('projects', '0002_alter_project_demo_video_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='courses.course'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='projects.project'),
        ),
    ]
