# Generated by Django 6.0.3 on 2026-06-17 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_orderitem_course_alter_orderitem_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='additional_remarks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
